# Configurações do Starship (https://starship.rs/config/)

format = """
$directory\
$git_branch\
$git_status\
$python\
$character\
"""

continuation_prompt = "> "
add_newline = false  # inserts a blank line between shell prompts

[directory]
truncate_to_repo = true	 # trunca no repositório pai quando for um projeto git
truncation_length = 0    # não trunca para demais repositórios

[python]
detect_extensions = []
detect_files = []
